### ISSUE TITLE
node.script: Trying to set the process_id for a child process, but it already has one

### ISSUE THREAD

**Issue by soklamon** [ircam-ismm/comote-helpers#1]
I get this error when trying to Initialize The QR code

**Comment by stefanodalessio** [comment]
+1

**Comment by b-ma** [comment]
Thanks for the report, I have also seen that log and also in other `node.script` use contexts, but it didn't crash the process nor seemed to create any issues, so it looked more like a Max issue to me. 

Does it prevent you to use the patch?

**Comment by stefanodalessio** [comment]
the patch works, but the qr code js frame stays blank

**Comment by b-ma** [comment]
Ok, could you try the new release of the Max patch and let us know if it is fixed on your side?

_edit:_
~https://github.com/ircam-ismm/comote-helpers/releases/tag/v0.3.3~
https://github.com/ircam-ismm/comote-helpers/releases/tag/v0.3.4

Thanks

**Comment by stefanodalessio** [comment]
working! thanks for the fix, btw for future readers: fix release is v0.3.4 at 
[https://github.com/ircam-ismm/comote-helpers/releases/tag/v0.3.4](https://github.com/ircam-ismm/comote-helpers/releases/tag/v0.3.4)

**Comment by b-ma** [comment]
Thanks for the feedback (and for the link fix)
